// <auto-generated />
using System;
using CarRentPlatform.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentPlatform.Persistence.Migrations
{
    [DbContext(typeof(CarRentPlatformDbContext))]
    [Migration("20260412175833_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentPlatform.Logic.Models.Car", b =>
                {
                    b.Property<Guid>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CarColor")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CarId");

                    b.HasIndex("ModelId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.CarPriceData", b =>
                {
                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LateReturnPenaltyPerDayBYN")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerDayBYN")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CarId");

                    b.ToTable("CarPriceDatas", t =>
                        {
                            t.HasCheckConstraint("CK_CarPriceData_LateReturnPenaltyPerDayBYN_Min", "[LateReturnPenaltyPerDayBYN] >= 0");

                            t.HasCheckConstraint("CK_CarPriceData_PricePerDayBYN_Min", "[PricePerDayBYN] >= 0");
                        });
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.CarReservationData", b =>
                {
                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CarReservationStatus")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ServiceTime")
                        .HasColumnType("time");

                    b.HasKey("CarId");

                    b.ToTable("CarReservationDatas");
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.Model", b =>
                {
                    b.Property<Guid>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ModelId");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.ModelSpecifications", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CarType")
                        .HasColumnType("int");

                    b.Property<float>("CityConsumptionPer100km")
                        .HasColumnType("real");

                    b.Property<float>("CityRangeKm")
                        .HasColumnType("real");

                    b.Property<int>("Fuel")
                        .HasColumnType("int");

                    b.Property<float>("HighwayConsumptionPer100km")
                        .HasColumnType("real");

                    b.Property<float>("HighwayRangeKm")
                        .HasColumnType("real");

                    b.Property<bool>("IsAutomaticTransmission")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfSeatsWithDriver")
                        .HasColumnType("int");

                    b.Property<float>("TankCapacity")
                        .HasColumnType("real");

                    b.Property<float>("TrunkVoluem")
                        .HasColumnType("real");

                    b.HasKey("ModelId");

                    b.ToTable("ModelSpecifications", t =>
                        {
                            t.HasCheckConstraint("CK_ModelSpecifications_CityConsumptionPer100km_Min", "[CityConsumptionPer100km] >= 0");

                            t.HasCheckConstraint("CK_ModelSpecifications_CityRangeKm_Min", "[CityRangeKm] >= 0");

                            t.HasCheckConstraint("CK_ModelSpecifications_HighwayConsumptionPer100km_Min", "[HighwayConsumptionPer100km] >= 0");

                            t.HasCheckConstraint("CK_ModelSpecifications_HighwayRangeKm_Min", "[HighwayRangeKm] >= 0");

                            t.HasCheckConstraint("CK_ModelSpecifications_NumberOfSeatsWithDriver_Min", "[NumberOfSeatsWithDriver] >= 1");

                            t.HasCheckConstraint("CK_ModelSpecifications_TankCapacity_Min", "[TankCapacity] >= 0");

                            t.HasCheckConstraint("CK_ModelSpecifications_TrunkVoluem_Min", "[TrunkVoluem] >= 0");
                        });
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.RentalPeriod", b =>
                {
                    b.Property<Guid>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("RentalPriceBYN")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PeriodId");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("RentalPeriods", t =>
                        {
                            t.HasCheckConstraint("CK_RentalPeriod_DateTimeStart_LessThan_DateTimeEnd", "[DateTimeStart] <= [DateTimeEnd]");

                            t.HasCheckConstraint("CK_RentalPeriod_RentalPriceBYN_Min", "[RentalPriceBYN] >= 0");
                        });
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.Role", b =>
                {
                    b.Property<int>("RoleNameId")
                        .HasColumnType("int");

                    b.Property<int>("CarsPermissions")
                        .HasColumnType("int");

                    b.Property<int>("ModelPermissions")
                        .HasColumnType("int");

                    b.Property<int>("RentalPeriodPermissions")
                        .HasColumnType("int");

                    b.Property<int>("RolePermissions")
                        .HasColumnType("int");

                    b.Property<int>("SelfPermissions")
                        .HasColumnType("int");

                    b.Property<int>("UserPermissions")
                        .HasColumnType("int");

                    b.HasKey("RoleNameId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleNameId = 1,
                            CarsPermissions = 2,
                            ModelPermissions = 2,
                            RentalPeriodPermissions = 2,
                            RolePermissions = 0,
                            SelfPermissions = 6,
                            UserPermissions = 0
                        },
                        new
                        {
                            RoleNameId = 2,
                            CarsPermissions = 15,
                            ModelPermissions = 15,
                            RentalPeriodPermissions = 15,
                            RolePermissions = 15,
                            SelfPermissions = 15,
                            UserPermissions = 15
                        },
                        new
                        {
                            RoleNameId = 3,
                            CarsPermissions = 2,
                            ModelPermissions = 2,
                            RentalPeriodPermissions = 2,
                            RolePermissions = 0,
                            SelfPermissions = 6,
                            UserPermissions = 2
                        },
                        new
                        {
                            RoleNameId = 4,
                            CarsPermissions = 2,
                            ModelPermissions = 2,
                            RentalPeriodPermissions = 15,
                            RolePermissions = 0,
                            SelfPermissions = 6,
                            UserPermissions = 2
                        },
                        new
                        {
                            RoleNameId = 5,
                            CarsPermissions = 15,
                            ModelPermissions = 15,
                            RentalPeriodPermissions = 15,
                            RolePermissions = 0,
                            SelfPermissions = 6,
                            UserPermissions = 0
                        },
                        new
                        {
                            RoleNameId = 6,
                            CarsPermissions = 0,
                            ModelPermissions = 0,
                            RentalPeriodPermissions = 0,
                            RolePermissions = 2,
                            SelfPermissions = 6,
                            UserPermissions = 15
                        });
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTimeCreation")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleNameId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleNameId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.UserAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.UserCondition", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserConditions", t =>
                        {
                            t.HasCheckConstraint("CK_User_Rating_Range", "[Rating] >= 0 AND [Rating] <= 10");
                        });
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.UserDocumentsData", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DriverLicenseCategory")
                        .HasColumnType("int");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("LicenseExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("UserDocumentsDatas");
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.Car", b =>
                {
                    b.HasOne("CarRentPlatform.Logic.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Model");
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.CarPriceData", b =>
                {
                    b.HasOne("CarRentPlatform.Logic.Models.Car", null)
                        .WithOne("CarPriceData")
                        .HasForeignKey("CarRentPlatform.Logic.Models.CarPriceData", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.CarReservationData", b =>
                {
                    b.HasOne("CarRentPlatform.Logic.Models.Car", null)
                        .WithOne("CarReservationData")
                        .HasForeignKey("CarRentPlatform.Logic.Models.CarReservationData", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.ModelSpecifications", b =>
                {
                    b.HasOne("CarRentPlatform.Logic.Models.Model", null)
                        .WithOne("ModelSpecifications")
                        .HasForeignKey("CarRentPlatform.Logic.Models.ModelSpecifications", "ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.RentalPeriod", b =>
                {
                    b.HasOne("CarRentPlatform.Logic.Models.CarReservationData", null)
                        .WithMany("OccupiedPeriods")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRentPlatform.Logic.Models.User", null)
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.User", b =>
                {
                    b.HasOne("CarRentPlatform.Logic.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.UserAccount", b =>
                {
                    b.HasOne("CarRentPlatform.Logic.Models.User", null)
                        .WithOne()
                        .HasForeignKey("CarRentPlatform.Logic.Models.UserAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.UserCondition", b =>
                {
                    b.HasOne("CarRentPlatform.Logic.Models.User", null)
                        .WithOne("UserCondition")
                        .HasForeignKey("CarRentPlatform.Logic.Models.UserCondition", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.UserDocumentsData", b =>
                {
                    b.HasOne("CarRentPlatform.Logic.Models.User", null)
                        .WithOne("UserDocumentsData")
                        .HasForeignKey("CarRentPlatform.Logic.Models.UserDocumentsData", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.Car", b =>
                {
                    b.Navigation("CarPriceData")
                        .IsRequired();

                    b.Navigation("CarReservationData")
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.CarReservationData", b =>
                {
                    b.Navigation("OccupiedPeriods");
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.Model", b =>
                {
                    b.Navigation("ModelSpecifications")
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentPlatform.Logic.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("UserCondition")
                        .IsRequired();

                    b.Navigation("UserDocumentsData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
